### PR TITLE
Update protocol-reference.md with V24 bucket info

### PR DESCRIPTION
**Pull request by qwahzi**
Updating from 129 to 62 buckets, per:
https://github.com/nanocurrency/nano-node/pull/3980

Updating from current block balance to max of current or previous, per: https://github.com/nanocurrency/nano-node/pull/4022

### CODE REVIEW

**Review by mistakia — APPROVED** [review]

**Comment by My1** [comment]
I'd rather say "new" instead of current for the comparative sentence, as it did iirc work based on the new block's balance and "current" would in theory when talking about the queue of transactions refer to the confirmed frontier, wouldnt it?

**Comment by mistakia** [comment]
> I'd rather say "new balance" instead of current for the comparative sentence, as it did iirc work based on the new block's balance and "current" would in theory when talking about the queue of transactions refer to the confirmed frontier, wouldnt it?

What about `frontier block balance`? Less ambiguous but maybe a little wordy/technical.

**Comment by My1** [comment]
well frontier can still meant the block that's the currently confirmed frontier, or the block in the bucket, which is also referred to as a frontier e.g. in the RPC.

**Comment by mistakia** [comment]
What about `checked frontier block balance`? and perhaps make `checked` a link to a glossary entry for `checked block`

**Comment by My1** [comment]
Tbh i don't even know which balance has actually been used in v22/23 but i would have expected the balance prior to the block you are trying to confirm, so the confirmed frontier. Otherwise you could just have moved your buckets around by a send/recieve including your unconfirmed things.

**Pull request merged**
