### PR TITLE
Update nano-reps.csv

### PR DESCRIPTION
**Pull request by jaumebosch**
Updated Nanovault entry

### CODE REVIEW

**Comment by mistakia** [comment]
@jaumebosch what are your thoughts on using the CLI (https://nano.community/cli) to manage your rep related metadata?

It would be good to have a way for representatives themselves to manage their metadata that is self authenticating (signed).

**Comment by jaumebosch** [comment]
nice! I'll try it. 
Just done the PR 'cause @qwahzi told me that was the way to update a nano node name

**Comment by qwahzi** [comment]
@mistakia Are there any thoughts on alternate verification methods? I think many people are going to be hesitant to use a method that requires configuring a private key somewhere, even though the key stays local

**Comment by mistakia** [comment]
Not sure there's a way to do it that doesn't involve the private key in some form (be it sending a transaction or a signed message). At the end of the day you need to demonstrate possession of the private key. 

I think the first step is polling rep managers to understand how/where they store their private key. That way we can have a better sense of what would be the most convenient ways to implement this.

My guess is the final form is making sure the wallets (or node) that they use has the ability to generate these signed messages which they can then send to the nano.community system (API or distributed network)

**Pull request closed without merging**
